SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET CHARACTER SET utf8mb4;

INSERT INTO Usuario (id, email, password, paquetes, paquetesPremium, intercambiosRealizados, monedas, activo, rol, pais)
VALUES (1, 'test@unlam.edu.ar', '123456789', 200, 200, 0, 100, true, 'USER', 'Argentina');

INSERT INTO Pais (id, codigo, nombre, grupo_album, orden_album, codigo_bandera)
VALUES
    (1, 'MEX', 'Mexico', 'A', 1, 'mx'),
    (2, 'RSA', 'Sudáfrica', 'A', 2, 'za'),
    (3, 'KOR', 'Corea del Sur', 'A', 3, 'kr'),
    (4, 'CZE', 'Chequia', 'A', 4, 'cz'),
    (5, 'CAN', 'Canadá', 'B', 5, 'ca'),
    (6, 'BIH', 'Bosnia-Herzegovina', 'B', 6, 'ba'),
    (7, 'QAT', 'Qatar', 'B', 7, 'qa'),
    (8, 'SUI', 'Suiza', 'B', 8, 'ch'),
    (9, 'BRA', 'Brasil', 'C', 9, 'br'),
    (10, 'MAR', 'Marruecos', 'C', 10, 'ma'),
    (11, 'HAI', 'Haití', 'C', 11, 'ht'),
    (12, 'SCO', 'Escocia', 'C', 12, 'gb-sct'),
    (13, 'USA', 'Estados Unidos', 'D', 13, 'us'),
    (14, 'PAR', 'Paraguay', 'D', 14, 'py'),
    (15, 'AUS', 'Australia', 'D', 15, 'au'),
    (16, 'TUR', 'Turquía', 'D', 16, 'tr'),
    (17, 'GER', 'Alemania', 'E', 17, 'de'),
    (18, 'CUW', 'Curazao', 'E', 18, 'cw'),
    (19, 'CIV', 'Costa de Marfil', 'E', 19, 'ci'),
    (20, 'ECU', 'Ecuador', 'E', 20, 'ec'),
    (21, 'NED', 'Países Bajos', 'F', 21, 'nl'),
    (22, 'JPN', 'Japón', 'F', 22, 'jp'),
    (23, 'SWE', 'Suecia', 'F', 23, 'se'),
    (24, 'TUN', 'Túnez', 'F', 24, 'tn'),
    (25, 'BEL', 'Bélgica', 'G', 25, 'be'),
    (26, 'EGY', 'Egipto', 'G', 26, 'eg'),
    (27, 'IRN', 'Irán', 'G', 27, 'ir'),
    (28, 'NZL', 'Nueva Zelanda', 'G', 28, 'nz'),
    (29, 'ESP', 'España', 'H', 29, 'es'),
    (30, 'CPV', 'Cabo Verde', 'H', 30, 'cv'),
    (31, 'KSA', 'Arabia Saudita', 'H', 31, 'sa'),
    (32, 'URU', 'Uruguay', 'H', 32, 'uy'),
    (33, 'FRA', 'Francia', 'I', 33, 'fr'),
    (34, 'SEN', 'Senegal', 'I', 34, 'sn'),
    (35, 'IRQ', 'Irak', 'I', 35, 'iq'),
    (36, 'NOR', 'Noruega', 'I', 36, 'no'),
    (37, 'ARG', 'Argentina', 'J', 37, 'ar'),
    (38, 'ALG', 'Argelia', 'J', 38, 'dz'),
    (39, 'AUT', 'Austria', 'J', 39, 'at'),
    (40, 'JOR', 'Jordania', 'J', 40, 'jo'),
    (41, 'POR', 'Portugal', 'K', 41, 'pt'),
    (42, 'COD', 'RD Congo', 'K', 42, 'cd'),
    (43, 'UZB', 'Uzbekistán', 'K', 43, 'uz'),
    (44, 'COL', 'Colombia', 'K', 44, 'co'),
    (45, 'ENG', 'Inglaterra', 'L', 45, 'gb-eng'),
    (46, 'CRO', 'Croacia', 'L', 46, 'hr'),
    (47, 'GHA', 'Ghana', 'L', 47, 'gh'),
    (48, 'PAN', 'Panamá', 'L', 48, 'pa');

INSERT INTO Figurita (id, nombre_jugador, pais_id, imagen_url, club, numero_dentro_del_pais, tipo)
VALUES
    (1, 'Escudo de Mexico', 1, null, null, 1, 'ESCUDO'),
    (2, 'Guillermo Ochoa', 1, null, 'AVS Futebol SAD (POR 1)', 2, 'TITULAR'),
    (3, 'Jorge Sánchez', 1, null, 'Cruz Azul (MEX 1)', 3, 'TITULAR'),
    (4, 'César Montes', 1, null, 'Almería (ESP 2)', 4, 'TITULAR'),
    (5, 'Johan Vásquez', 1, null, 'Genoa (ITA 1)', 5, 'TITULAR'),
    (6, 'Jesús Gallardo', 1, null, 'Toluca (MEX 1)', 6, 'TITULAR'),
    (7, 'Edson Álvarez', 1, null, 'West Ham United (ENG 1)', 7, 'TITULAR'),
    (8, 'Luis Chávez', 1, null, 'Dinamo Moscú (RUS 1)', 8, 'TITULAR'),
    (9, 'Orbelín Pineda', 1, null, 'AEK Atenas (GRE 1)', 9, 'TITULAR'),
    (10, 'Roberto Alvarado', 1, null, 'Guadalajara/Chivas (MEX 1)', 10, 'TITULAR'),
    (11, 'Santiago Giménez', 1, null, 'AC Milan (ITA 1)', 11, 'TITULAR'),
    (12, 'Julián Quiñones', 1, null, 'Al-Qadsiah (KSA 1)', 12, 'TITULAR'),
    (13, 'Escudo de Sudáfrica', 2, null, null, 1, 'ESCUDO'),
    (14, 'Ronwen Williams', 2, null, 'Mamelodi Sundowns (RSA 1)', 2, 'TITULAR'),
    (15, 'Khuliso Mudau', 2, null, 'Mamelodi Sundowns (RSA 1)', 3, 'TITULAR'),
    (16, 'Siyanda Xulu', 2, null, 'SuperSport United (RSA 1)', 4, 'TITULAR'),
    (17, 'Mothobi Mvala', 2, null, 'Mamelodi Sundowns (RSA 1)', 5, 'TITULAR'),
    (18, 'Aubrey Modiba', 2, null, 'Mamelodi Sundowns (RSA 1)', 6, 'TITULAR'),
    (19, 'Teboho Mokoena', 2, null, 'Mamelodi Sundowns (RSA 1)', 7, 'TITULAR'),
    (20, 'Sphephelo Sithole', 2, null, 'Tondela (POR 2)', 8, 'TITULAR'),
    (21, 'Themba Zwane', 2, null, 'Mamelodi Sundowns (RSA 1)', 9, 'TITULAR'),
    (22, 'Percy Tau', 2, null, 'Al Ahly (EGY 1)', 10, 'TITULAR'),
    (23, 'Lyle Foster', 2, null, 'Burnley (ENG 2)', 11, 'TITULAR'),
    (24, 'Thapelo Morena', 2, null, 'Mamelodi Sundowns (RSA 1)', 12, 'TITULAR'),
    (25, 'Escudo de Corea del Sur', 3, null, null, 1, 'ESCUDO'),
    (26, 'Jo Hyun-Woo', 3, null, 'Ulsan HD (KOR 1)', 2, 'TITULAR'),
    (27, 'Seol Young-Woo', 3, null, 'Estrella Roja (SRB 1)', 3, 'TITULAR'),
    (28, 'Kim Min-Jae', 3, null, 'Bayern Múnich (GER 1)', 4, 'TITULAR'),
    (29, 'Kim Tae-Hyun', 3, null, 'Sagan Tosu (JPN 2)', 5, 'TITULAR'),
    (30, 'Lee Tae-Seok', 3, null, 'Pohang Steelers (KOR 1)', 6, 'TITULAR'),
    (31, 'Hwang In-Beom', 3, null, 'Feyenoord (NED 1)', 7, 'TITULAR'),
    (32, 'Paik Seung-Ho', 3, null, 'Birmingham City (ENG 3)', 8, 'TITULAR'),
    (33, 'Lee Kang-In', 3, null, 'Paris Saint-Germain (FRA 1)', 9, 'TITULAR'),
    (34, 'Lee Jae-Sung', 3, null, 'Mainz 05 (GER 1)', 10, 'TITULAR'),
    (35, 'Son Heung-Min', 3, null, 'Tottenham Hotspur (ENG 1)', 11, 'TITULAR'),
    (36, 'Cho Kyu-Sung', 3, null, 'Midtjylland (DEN 1)', 12, 'TITULAR'),
    (37, 'Escudo de Chequia', 4, null, null, 1, 'ESCUDO'),
    (38, 'Matej Kovar', 4, null, 'Bayer Leverkusen (GER 1)', 2, 'TITULAR'),
    (39, 'Vladimír Coufal', 4, null, 'West Ham United (ENG 1)', 3, 'TITULAR'),
    (40, 'Martin Vitík', 4, null, 'Sparta Praga (CZE 1)', 4, 'TITULAR'),
    (41, 'Ladislav Krejčí', 4, null, 'Girona (ESP 1)', 5, 'TITULAR'),
    (42, 'David Jurásek', 4, null, 'Hoffenheim (GER 1)', 6, 'TITULAR'),
    (43, 'Tomáš Souček', 4, null, 'West Ham United (ENG 1)', 7, 'TITULAR'),
    (44, 'Lukáš Červ', 4, null, 'Viktoria PlzeÅˆ (CZE 1)', 8, 'TITULAR'),
    (45, 'Pavel Å ulc', 4, null, 'Viktoria PlzeÅˆ (CZE 1)', 9, 'TITULAR'),
    (46, 'Adam HloÅ¾ek', 4, null, 'Hoffenheim (GER 1)', 10, 'TITULAR'),
    (47, 'Patrik Schick', 4, null, 'Bayer Leverkusen (GER 1)', 11, 'TITULAR'),
    (48, 'Lukáš Provod', 4, null, 'Slavia Praga (CZE 1)', 12, 'TITULAR'),
    (49, 'Escudo de Canadá', 5, null, null, 1, 'ESCUDO'),
    (50, 'Maxime Crépeau', 5, null, 'Portland Timbers (USA 1)', 2, 'TITULAR'),
    (51, 'Alistair Johnston', 5, null, 'Celtic (SCO 1)', 3, 'TITULAR'),
    (52, 'Moïse Bombito', 5, null, 'Nice (FRA 1)', 4, 'TITULAR'),
    (53, 'Derek Cornelius', 5, null, 'Olympique Marsella (FRA 1)', 5, 'TITULAR'),
    (54, 'Alphonso Davies', 5, null, 'Bayern Múnich (GER 1)', 6, 'TITULAR'),
    (55, 'Stephen Eustáquio', 5, null, 'Porto (POR 1)', 7, 'TITULAR'),
    (56, 'Ismaël Koné', 5, null, 'Olympique Marsella (FRA 1)', 8, 'TITULAR'),
    (57, 'Tajon Buchanan', 5, null, 'Inter de Milán (ITA 1)', 9, 'TITULAR'),
    (58, 'Jonathan David', 5, null, 'Lille (FRA 1)', 10, 'TITULAR'),
    (59, 'Jacob Shaffelburg', 5, null, 'Nashville SC (USA 1)', 11, 'TITULAR'),
    (60, 'Cyle Larin', 5, null, 'Mallorca (ESP 1)', 12, 'TITULAR'),
    (61, 'Escudo de Bosnia-Herzegovina', 6, null, null, 1, 'ESCUDO'),
    (62, 'Nikola Vasilj', 6, null, 'St. Pauli (GER 1)', 2, 'TITULAR'),
    (63, 'Amar DediÄ‡', 6, null, 'Olympique Marsella (FRA 1)', 3, 'TITULAR'),
    (64, 'Nikola KatiÄ‡', 6, null, 'Zürich (SUI 1)', 4, 'TITULAR'),
    (65, 'Sead KolaÅ¡inac', 6, null, 'Atalanta (ITA 1)', 5, 'TITULAR'),
    (66, 'Nihad MujakiÄ‡', 6, null, 'Ankaragücü (TUR 2)', 6, 'TITULAR'),
    (67, 'Amir HadÅ¾iahmetoviÄ‡', 6, null, 'BeÅŸiktaÅŸ (TUR 1)', 7, 'TITULAR'),
    (68, 'Benjamin TahiroviÄ‡', 6, null, 'Brøndby (DEN 1)', 8, 'TITULAR'),
    (69, 'Esmir BajraktareviÄ‡', 6, null, 'PSV Eindhoven (NED 1)', 9, 'TITULAR'),
    (70, 'Ermedin DemiroviÄ‡', 6, null, 'Stuttgart (GER 1)', 10, 'TITULAR'),
    (71, 'Edin DÅ¾eko', 6, null, 'Fenerbahçe (TUR 1)', 11, 'TITULAR'),
    (72, 'Haris TabakoviÄ‡', 6, null, 'Hoffenheim (GER 1)', 12, 'TITULAR'),
    (73, 'Escudo de Qatar', 7, null, null, 1, 'ESCUDO'),
    (74, 'Meshaal Barsham', 7, null, 'Al Sadd (QAT 1)', 2, 'TITULAR'),
    (75, 'Pedro Miguel', 7, null, 'Al Sadd (QAT 1)', 3, 'TITULAR'),
    (76, 'Boualem Khoukhi', 7, null, 'Al Sadd (QAT 1)', 4, 'TITULAR'),
    (77, 'Lucas Mendes', 7, null, 'Al Wakrah (QAT 1)', 5, 'TITULAR'),
    (78, 'Sultan Al-Brake', 7, null, 'Al Duhail (QAT 1)', 6, 'TITULAR'),
    (79, 'Mohammed Waad', 7, null, 'Al Sadd (QAT 1)', 7, 'TITULAR'),
    (80, 'Assim Madibo', 7, null, 'Al Duhail (QAT 1)', 8, 'TITULAR'),
    (81, 'Hassan Al-Haydos', 7, null, 'Al Sadd (QAT 1)', 9, 'TITULAR'),
    (82, 'Akram Afif', 7, null, 'Al Sadd (QAT 1)', 10, 'TITULAR'),
    (83, 'Almoez Ali', 7, null, 'Al Duhail (QAT 1)', 11, 'TITULAR'),
    (84, 'Ahmed Alaaeldin', 7, null, 'Al Gharafa (QAT 1)', 12, 'TITULAR'),
    (85, 'Escudo de Suiza', 8, null, null, 1, 'ESCUDO'),
    (86, 'Gregor Kobel', 8, null, 'Borussia Dortmund (GER 1)', 2, 'TITULAR'),
    (87, 'Silvan Widmer', 8, null, 'Mainz 05 (GER 1)', 3, 'TITULAR'),
    (88, 'Manuel Akanji', 8, null, 'Manchester City (ENG 1)', 4, 'TITULAR'),
    (89, 'Nico Elvedi', 8, null, 'Borussia Mönchengladbach (GER 1)', 5, 'TITULAR'),
    (90, 'Ricardo Rodríguez', 8, null, 'Betis (ESP 1)', 6, 'TITULAR'),
    (91, 'Granit Xhaka', 8, null, 'Bayer Leverkusen (GER 1)', 7, 'TITULAR'),
    (92, 'Remo Freuler', 8, null, 'Bologna (ITA 1)', 8, 'TITULAR'),
    (93, 'Denis Zakaria', 8, null, 'Monaco (FRA 1)', 9, 'TITULAR'),
    (94, 'Dan Ndoye', 8, null, 'Bologna (ITA 1)', 10, 'TITULAR'),
    (95, 'Breel Embolo', 8, null, 'Monaco (FRA 1)', 11, 'TITULAR'),
    (96, 'Noah Okafor', 8, null, 'Napoli (ITA 1)', 12, 'TITULAR'),
    (97, 'Escudo de Brasil', 9, null, null, 1, 'ESCUDO'),
    (98, 'Alisson', 9, null, 'Liverpool (ENG 1)', 2, 'TITULAR'),
    (99, 'Wesley', 9, null, 'Flamengo (BRA 1)', 3, 'TITULAR'),
    (100, 'Marquinhos', 9, null, 'Paris Saint-Germain (FRA 1)', 4, 'TITULAR'),
    (101, 'Gabriel Magalhães', 9, null, 'Arsenal (ENG 1)', 5, 'TITULAR'),
    (102, 'Alex Sandro', 9, null, 'Flamengo (BRA 1)', 6, 'TITULAR'),
    (103, 'Casemiro', 9, null, 'Manchester United (ENG 1)', 7, 'TITULAR'),
    (104, 'Bruno Guimarães', 9, null, 'Newcastle United (ENG 1)', 8, 'TITULAR'),
    (105, 'Lucas Paquetá', 9, null, 'West Ham United (ENG 1)', 9, 'TITULAR'),
    (106, 'Raphinha', 9, null, 'Barcelona (ESP 1)', 10, 'TITULAR'),
    (107, 'Neymar', 9, null, 'Santos (BRA 1)', 11, 'TITULAR'),
    (108, 'Vinícius Júnior', 9, null, 'Real Madrid (ESP 1)', 12, 'TITULAR'),
    (109, 'Escudo de Marruecos', 10, null, null, 1, 'ESCUDO'),
    (110, 'Yassine Bounou', 10, null, 'Al Hilal (KSA 1)', 2, 'TITULAR'),
    (111, 'Achraf Hakimi', 10, null, 'Paris Saint-Germain (FRA 1)', 3, 'TITULAR'),
    (112, 'Nayef Aguerd', 10, null, 'Real Sociedad (ESP 1)', 4, 'TITULAR'),
    (113, 'Romain Saïss', 10, null, 'Al Sadd (QAT 1)', 5, 'TITULAR'),
    (114, 'Noussair Mazraoui', 10, null, 'Manchester United (ENG 1)', 6, 'TITULAR'),
    (115, 'Sofyan Amrabat', 10, null, 'Fenerbahçe (TUR 1)', 7, 'TITULAR'),
    (116, 'Azzedine Ounahi', 10, null, 'Panathinaikos (GRE 1)', 8, 'TITULAR'),
    (117, 'Bilal El Khannouss', 10, null, 'Leicester City (ENG 1)', 9, 'TITULAR'),
    (118, 'Hakim Ziyech', 10, null, 'Al Duhail (QAT 1)', 10, 'TITULAR'),
    (119, 'Youssef En-Nesyri', 10, null, 'Fenerbahçe (TUR 1)', 11, 'TITULAR'),
    (120, 'Brahim Díaz', 10, null, 'Real Madrid (ESP 1)', 12, 'TITULAR'),
    (121, 'Escudo de Haití', 11, null, null, 1, 'ESCUDO'),
    (122, 'Johny Placide', 11, null, 'Bastia (FRA 2)', 2, 'TITULAR'),
    (123, 'Carlens Arcus', 11, null, 'Angers (FRA 1)', 3, 'TITULAR'),
    (124, 'Ricardo Adé', 11, null, 'LDU Quito (ECU 1)', 4, 'TITULAR'),
    (125, 'Jean-Kévin Duverne', 11, null, 'Nantes (FRA 1)', 5, 'TITULAR'),
    (126, 'Hannes Delcroix', 11, null, 'Burnley (ENG 2)', 6, 'TITULAR'),
    (127, 'Carl Fred Sainte', 11, null, 'Dallas (USA 1)', 7, 'TITULAR'),
    (128, 'Danley Jean Jacques', 11, null, 'Metz (FRA 2)', 8, 'TITULAR'),
    (129, 'Jean-Ricner Bellegarde', 11, null, 'Wolverhampton (ENG 1)', 9, 'TITULAR'),
    (130, 'Derrick Etienne', 11, null, 'Toronto FC (CAN/USA 1)', 10, 'TITULAR'),
    (131, 'Duckens Nazon', 11, null, 'Kayserispor (TUR 1)', 11, 'TITULAR'),
    (132, 'Frantzdy Pierrot', 11, null, 'AEK Atenas (GRE 1)', 12, 'TITULAR'),
    (133, 'Escudo de Escocia', 12, null, null, 1, 'ESCUDO'),
    (134, 'Angus Gunn', 12, null, 'Norwich City (ENG 2)', 2, 'TITULAR'),
    (135, 'Aaron Hickey', 12, null, 'Brentford (ENG 1)', 3, 'TITULAR'),
    (136, 'Jack Hendry', 12, null, 'Al Ettifaq (KSA 1)', 4, 'TITULAR'),
    (137, 'Scott McKenna', 12, null, 'Las Palmas (ESP 1)', 5, 'TITULAR'),
    (138, 'Andy Robertson', 12, null, 'Liverpool (ENG 1)', 6, 'TITULAR'),
    (139, 'Billy Gilmour', 12, null, 'Napoli (ITA 1)', 7, 'TITULAR'),
    (140, 'Scott McTominay', 12, null, 'Napoli (ITA 1)', 8, 'TITULAR'),
    (141, 'John McGinn', 12, null, 'Aston Villa (ENG 1)', 9, 'TITULAR'),
    (142, 'Ryan Christie', 12, null, 'Bournemouth (ENG 1)', 10, 'TITULAR'),
    (143, 'Ché Adams', 12, null, 'Torino (ITA 1)', 11, 'TITULAR'),
    (144, 'Kieran Tierney', 12, null, 'Arsenal (ENG 1)', 12, 'TITULAR'),
    (145, 'Escudo de Estados Unidos', 13, null, null, 1, 'ESCUDO'),
    (146, 'Matt Turner', 13, null, 'Crystal Palace (ENG 1)', 2, 'TITULAR'),
    (147, 'Sergiño Dest', 13, null, 'PSV Eindhoven (NED 1)', 3, 'TITULAR'),
    (148, 'Chris Richards', 13, null, 'Crystal Palace (ENG 1)', 4, 'TITULAR'),
    (149, 'Tim Ream', 13, null, 'Charlotte FC (USA 1)', 5, 'TITULAR'),
    (150, 'Antonee Robinson', 13, null, 'Fulham (ENG 1)', 6, 'TITULAR'),
    (151, 'Tyler Adams', 13, null, 'Bournemouth (ENG 1)', 7, 'TITULAR'),
    (152, 'Weston McKennie', 13, null, 'Juventus (ITA 1)', 8, 'TITULAR'),
    (153, 'Yunus Musah', 13, null, 'AC Milan (ITA 1)', 9, 'TITULAR'),
    (154, 'Timothy Weah', 13, null, 'Juventus (ITA 1)', 10, 'TITULAR'),
    (155, 'Folarin Balogun', 13, null, 'Monaco (FRA 1)', 11, 'TITULAR'),
    (156, 'Christian Pulisic', 13, null, 'AC Milan (ITA 1)', 12, 'TITULAR'),
    (157, 'Escudo de Paraguay', 14, null, null, 1, 'ESCUDO'),
    (158, 'Gatito Fernández', 14, null, 'Cerro Porteño (PAR 1)', 2, 'TITULAR'),
    (159, 'Gustavo Gómez', 14, null, 'Palmeiras (BRA 1)', 3, 'TITULAR'),
    (160, 'Fabián Balbuena', 14, null, 'Dinamo Moscú (RUS 1)', 4, 'TITULAR'),
    (161, 'Omar Alderete', 14, null, 'Getafe (ESP 1)', 5, 'TITULAR'),
    (162, 'Junior Alonso', 14, null, 'Atlético Mineiro (BRA 1)', 6, 'TITULAR'),
    (163, 'Andrés Cubas', 14, null, 'Vancouver Whitecaps (CAN/USA 1)', 7, 'TITULAR'),
    (164, 'Mathías Villasanti', 14, null, 'Grêmio (BRA 1)', 8, 'TITULAR'),
    (165, 'Miguel Almirón', 14, null, 'Atlanta United (USA 1)', 9, 'TITULAR'),
    (166, 'Ramón Sosa', 14, null, 'Nottingham Forest (ENG 1)', 10, 'TITULAR'),
    (167, 'Antonio Sanabria', 14, null, 'Torino (ITA 1)', 11, 'TITULAR'),
    (168, 'Julio Enciso', 14, null, 'Ipswich Town (ENG 1)', 12, 'TITULAR'),
    (169, 'Escudo de Australia', 15, null, null, 1, 'ESCUDO'),
    (170, 'Mathew Ryan', 15, null, 'Lens (FRA 1)', 2, 'TITULAR'),
    (171, 'Nathaniel Atkinson', 15, null, 'Heart of Midlothian (SCO 1)', 3, 'TITULAR'),
    (172, 'Harry Souttar', 15, null, 'Sheffield United (ENG 2)', 4, 'TITULAR'),
    (173, 'Kye Rowles', 15, null, 'DC United (USA 1)', 5, 'TITULAR'),
    (174, 'Jordan Bos', 15, null, 'Westerlo (BEL 1)', 6, 'TITULAR'),
    (175, 'Jackson Irvine', 15, null, 'St. Pauli (GER 1)', 7, 'TITULAR'),
    (176, 'Aiden O’Neill', 15, null, 'Standard Lieja (BEL 1)', 8, 'TITULAR'),
    (177, 'Martin Boyle', 15, null, 'Hibernian (SCO 1)', 9, 'TITULAR'),
    (178, 'Ajdin Hrustic', 15, null, 'Salernitana (ITA 2)', 10, 'TITULAR'),
    (179, 'Craig Goodwin', 15, null, 'Al Wehda (KSA 1)', 11, 'TITULAR'),
    (180, 'Mitchell Duke', 15, null, 'Machida Zelvia (JPN 1)', 12, 'TITULAR'),
    (181, 'Escudo de Turquía', 16, null, null, 1, 'ESCUDO'),
    (182, 'Uğurcan Çakır', 16, null, 'Trabzonspor (TUR 1)', 2, 'TITULAR'),
    (183, 'Mert Müldür', 16, null, 'Fenerbahçe (TUR 1)', 3, 'TITULAR'),
    (184, 'Merih Demiral', 16, null, 'Al Ahli (KSA 1)', 4, 'TITULAR'),
    (185, 'Abdülkerim Bardakcı', 16, null, 'Galatasaray (TUR 1)', 5, 'TITULAR'),
    (186, 'Ferdi KadÄ±oÄŸlu', 16, null, 'Brighton (ENG 1)', 6, 'TITULAR'),
    (187, 'Hakan Çalhanoğlu', 16, null, 'Inter de Milán (ITA 1)', 7, 'TITULAR'),
    (188, 'İsmail Yüksek', 16, null, 'Fenerbahçe (TUR 1)', 8, 'TITULAR'),
    (189, 'Orkun Kökçü', 16, null, 'Benfica (POR 1)', 9, 'TITULAR'),
    (190, 'Arda Güler', 16, null, 'Real Madrid (ESP 1)', 10, 'TITULAR'),
    (191, 'Kerem Aktürkoğlu', 16, null, 'Benfica (POR 1)', 11, 'TITULAR'),
    (192, 'Kenan YÄ±ldÄ±z', 16, null, 'Juventus (ITA 1)', 12, 'TITULAR'),
    (193, 'Escudo de Alemania', 17, null, null, 1, 'ESCUDO'),
    (194, 'Manuel Neuer', 17, null, 'Bayern Múnich (GER 1)', 2, 'TITULAR'),
    (195, 'Joshua Kimmich', 17, null, 'Bayern Múnich (GER 1)', 3, 'TITULAR'),
    (196, 'Antonio Rüdiger', 17, null, 'Real Madrid (ESP 1)', 4, 'TITULAR'),
    (197, 'Jonathan Tah', 17, null, 'Bayer Leverkusen (GER 1)', 5, 'TITULAR'),
    (198, 'David Raum', 17, null, 'RB Leipzig (GER 1)', 6, 'TITULAR'),
    (199, 'Robert Andrich', 17, null, 'Bayer Leverkusen (GER 1)', 7, 'TITULAR'),
    (200, 'Aleksandar PavloviÄ‡', 17, null, 'Bayern Múnich (GER 1)', 8, 'TITULAR'),
    (201, 'Jamal Musiala', 17, null, 'Bayern Múnich (GER 1)', 9, 'TITULAR'),
    (202, 'Leroy Sané', 17, null, 'Bayern Múnich (GER 1)', 10, 'TITULAR'),
    (203, 'Kai Havertz', 17, null, 'Arsenal (ENG 1)', 11, 'TITULAR'),
    (204, 'Florian Wirtz', 17, null, 'Bayer Leverkusen (GER 1)', 12, 'TITULAR'),
    (205, 'Escudo de Curazao', 18, null, null, 1, 'ESCUDO'),
    (206, 'Eloy Room', 18, null, 'Vitesse (NED 2)', 2, 'TITULAR'),
    (207, 'Jurien Gaari', 18, null, 'RKC Waalwijk (NED 1)', 3, 'TITULAR'),
    (208, 'Cuco Martina', 18, null, 'NAC Breda (NED 1)', 4, 'TITULAR'),
    (209, 'Roshon van Eijma', 18, null, 'TOP Oss (NED 2)', 5, 'TITULAR'),
    (210, 'Sherel Floranus', 18, null, 'PEC Zwolle (NED 1)', 6, 'TITULAR'),
    (211, 'Vurnon Anita', 18, null, 'Al-Orobah (KSA 1)', 7, 'TITULAR'),
    (212, 'Leandro Bacuna', 18, null, 'Groningen (NED 1)', 8, 'TITULAR'),
    (213, 'Juninho Bacuna', 18, null, 'Birmingham City (ENG 3)', 9, 'TITULAR'),
    (214, 'Brandley Kuwas', 18, null, 'Giresunspor (TUR 2)', 10, 'TITULAR'),
    (215, 'Rangelo Janga', 18, null, 'Nea Salamina (CYP 1)', 11, 'TITULAR'),
    (216, 'Jarchinio Antonia', 18, null, 'Kozakken Boys (NED 3)', 12, 'TITULAR'),
    (217, 'Escudo de Costa de Marfil', 19, null, null, 1, 'ESCUDO'),
    (218, 'Yahia Fofana', 19, null, 'Angers (FRA 1)', 2, 'TITULAR'),
    (219, 'Wilfried Singo', 19, null, 'Monaco (FRA 1)', 3, 'TITULAR'),
    (220, 'Odilon Kossounou', 19, null, 'Atalanta (ITA 1)', 4, 'TITULAR'),
    (221, 'Evan Ndicka', 19, null, 'Roma (ITA 1)', 5, 'TITULAR'),
    (222, 'Ghislain Konan', 19, null, 'Al Fayha (KSA 1)', 6, 'TITULAR'),
    (223, 'Franck Kessié', 19, null, 'Al Ahli (KSA 1)', 7, 'TITULAR'),
    (224, 'Seko Fofana', 19, null, 'Rennes (FRA 1)', 8, 'TITULAR'),
    (225, 'Jean Michaël Seri', 19, null, 'Al-Orobah (KSA 1)', 9, 'TITULAR'),
    (226, 'Nicolas Pépé', 19, null, 'Villarreal (ESP 1)', 10, 'TITULAR'),
    (227, 'Sébastien Haller', 19, null, 'Utrecht (NED 1)', 11, 'TITULAR'),
    (228, 'Simon Adingra', 19, null, 'Brighton (ENG 1)', 12, 'TITULAR'),
    (229, 'Escudo de Ecuador', 20, null, null, 1, 'ESCUDO'),
    (230, 'Hernán Galíndez', 20, null, 'Huracán (ARG 1)', 2, 'TITULAR'),
    (231, 'Angelo Preciado', 20, null, 'Sparta Praga (CZE 1)', 3, 'TITULAR'),
    (232, 'Willian Pacho', 20, null, 'Paris Saint-Germain (FRA 1)', 4, 'TITULAR'),
    (233, 'Piero Hincapié', 20, null, 'Bayer Leverkusen (GER 1)', 5, 'TITULAR'),
    (234, 'Pervis Estupiñán', 20, null, 'Brighton (ENG 1)', 6, 'TITULAR'),
    (235, 'Moisés Caicedo', 20, null, 'Chelsea (ENG 1)', 7, 'TITULAR'),
    (236, 'Carlos Gruezo', 20, null, 'San Jose Earthquakes (USA 1)', 8, 'TITULAR'),
    (237, 'Kendry Páez', 20, null, 'Independiente del Valle (ECU 1)', 9, 'TITULAR'),
    (238, 'Gonzalo Plata', 20, null, 'Flamengo (BRA 1)', 10, 'TITULAR'),
    (239, 'Enner Valencia', 20, null, 'Internacional (BRA 1)', 11, 'TITULAR'),
    (240, 'Jeremy Sarmiento', 20, null, 'Burnley (ENG 2)', 12, 'TITULAR'),
    (241, 'Escudo de Países Bajos', 21, null, null, 1, 'ESCUDO'),
    (242, 'Bart Verbruggen', 21, null, 'Brighton (ENG 1)', 2, 'TITULAR'),
    (243, 'Denzel Dumfries', 21, null, 'Inter de Milán (ITA 1)', 3, 'TITULAR'),
    (244, 'Matthijs de Ligt', 21, null, 'Manchester United (ENG 1)', 4, 'TITULAR'),
    (245, 'Virgil van Dijk', 21, null, 'Liverpool (ENG 1)', 5, 'TITULAR'),
    (246, 'Nathan Aké', 21, null, 'Manchester City (ENG 1)', 6, 'TITULAR'),
    (247, 'Frenkie de Jong', 21, null, 'Barcelona (ESP 1)', 7, 'TITULAR'),
    (248, 'Tijjani Reijnders', 21, null, 'AC Milan (ITA 1)', 8, 'TITULAR'),
    (249, 'Xavi Simons', 21, null, 'RB Leipzig (GER 1)', 9, 'TITULAR'),
    (250, 'Donyell Malen', 21, null, 'Aston Villa (ENG 1)', 10, 'TITULAR'),
    (251, 'Memphis Depay', 21, null, 'Corinthians (BRA 1)', 11, 'TITULAR'),
    (252, 'Cody Gakpo', 21, null, 'Liverpool (ENG 1)', 12, 'TITULAR'),
    (253, 'Escudo de Japón', 22, null, null, 1, 'ESCUDO'),
    (254, 'Zion Suzuki', 22, null, 'Parma (ITA 1)', 2, 'TITULAR'),
    (255, 'Yukinari Sugawara', 22, null, 'Southampton (ENG 1)', 3, 'TITULAR'),
    (256, 'Ko Itakura', 22, null, 'Borussia Mönchengladbach (GER 1)', 4, 'TITULAR'),
    (257, 'Takehiro Tomiyasu', 22, null, 'Arsenal (ENG 1)', 5, 'TITULAR'),
    (258, 'Hiroki Ito', 22, null, 'Bayern Múnich (GER 1)', 6, 'TITULAR'),
    (259, 'Wataru Endo', 22, null, 'Liverpool (ENG 1)', 7, 'TITULAR'),
    (260, 'Ao Tanaka', 22, null, 'Leeds United (ENG 2)', 8, 'TITULAR'),
    (261, 'Daichi Kamada', 22, null, 'Crystal Palace (ENG 1)', 9, 'TITULAR'),
    (262, 'Takefusa Kubo', 22, null, 'Real Sociedad (ESP 1)', 10, 'TITULAR'),
    (263, 'Ayase Ueda', 22, null, 'Feyenoord (NED 1)', 11, 'TITULAR'),
    (264, 'Keito Nakamura', 22, null, 'Reims (FRA 1)', 12, 'TITULAR'),
    (265, 'Escudo de Suecia', 23, null, null, 1, 'ESCUDO'),
    (266, 'Viktor Johansson', 23, null, 'Stoke City (ENG 2)', 2, 'TITULAR'),
    (267, 'Emil Holm', 23, null, 'Bologna (ITA 1)', 3, 'TITULAR'),
    (268, 'Isak Hien', 23, null, 'Atalanta (ITA 1)', 4, 'TITULAR'),
    (269, 'Victor Lindelöf', 23, null, 'Manchester United (ENG 1)', 5, 'TITULAR'),
    (270, 'Gabriel Gudmundsson', 23, null, 'Lille (FRA 1)', 6, 'TITULAR'),
    (271, 'Jesper Karlström', 23, null, 'Udinese (ITA 1)', 7, 'TITULAR'),
    (272, 'Lucas Bergvall', 23, null, 'Tottenham Hotspur (ENG 1)', 8, 'TITULAR'),
    (273, 'Yasin Ayari', 23, null, 'Brighton (ENG 1)', 9, 'TITULAR'),
    (274, 'Anthony Elanga', 23, null, 'Nottingham Forest (ENG 1)', 10, 'TITULAR'),
    (275, 'Viktor Gyökeres', 23, null, 'Sporting CP (POR 1)', 11, 'TITULAR'),
    (276, 'Alexander Isak', 23, null, 'Newcastle United (ENG 1)', 12, 'TITULAR'),
    (277, 'Escudo de Túnez', 24, null, null, 1, 'ESCUDO'),
    (278, 'Aymen Dahmen', 24, null, 'CS Sfaxien (TUN 1)', 2, 'TITULAR'),
    (279, 'Yan Valery', 24, null, 'Sheffield Wednesday (ENG 2)', 3, 'TITULAR'),
    (280, 'Montassar Talbi', 24, null, 'Lorient (FRA 2)', 4, 'TITULAR'),
    (281, 'Dylan Bronn', 24, null, 'Salernitana (ITA 2)', 5, 'TITULAR'),
    (282, 'Ali Abdi', 24, null, 'Nice (FRA 1)', 6, 'TITULAR'),
    (283, 'Ellyes Skhiri', 24, null, 'Eintracht Frankfurt (GER 1)', 7, 'TITULAR'),
    (284, 'Hannibal Mejbri', 24, null, 'Burnley (ENG 2)', 8, 'TITULAR'),
    (285, 'Anis Ben Slimane', 24, null, 'Sheffield United (ENG 2)', 9, 'TITULAR'),
    (286, 'Elias Achouri', 24, null, 'FC Copenhague (DEN 1)', 10, 'TITULAR'),
    (287, 'Elias Saad', 24, null, 'St. Pauli (GER 1)', 11, 'TITULAR'),
    (288, 'Firas Chaouat', 24, null, 'CS Sfaxien (TUN 1)', 12, 'TITULAR'),
    (289, 'Escudo de Bélgica', 25, null, null, 1, 'ESCUDO'),
    (290, 'Thibaut Courtois', 25, null, 'Real Madrid (ESP 1)', 2, 'TITULAR'),
    (291, 'Timothy Castagne', 25, null, 'Fulham (ENG 1)', 3, 'TITULAR'),
    (292, 'Wout Faes', 25, null, 'Leicester City (ENG 1)', 4, 'TITULAR'),
    (293, 'Arthur Theate', 25, null, 'Eintracht Frankfurt (GER 1)', 5, 'TITULAR'),
    (294, 'Maxim De Cuyper', 25, null, 'Club Brugge (BEL 1)', 6, 'TITULAR'),
    (295, 'Amadou Onana', 25, null, 'Aston Villa (ENG 1)', 7, 'TITULAR'),
    (296, 'Youri Tielemans', 25, null, 'Aston Villa (ENG 1)', 8, 'TITULAR'),
    (297, 'Kevin De Bruyne', 25, null, 'Manchester City (ENG 1)', 9, 'TITULAR'),
    (298, 'Jérémy Doku', 25, null, 'Manchester City (ENG 1)', 10, 'TITULAR'),
    (299, 'Romelu Lukaku', 25, null, 'Napoli (ITA 1)', 11, 'TITULAR'),
    (300, 'Leandro Trossard', 25, null, 'Arsenal (ENG 1)', 12, 'TITULAR'),
    (301, 'Escudo de Egipto', 26, null, null, 1, 'ESCUDO'),
    (302, 'Mohamed El Shenawy', 26, null, 'Al Ahly (EGY 1)', 2, 'TITULAR'),
    (303, 'Mohamed Hany', 26, null, 'Al Ahly (EGY 1)', 3, 'TITULAR'),
    (304, 'Mohamed Abdelmonem', 26, null, 'Nice (FRA 1)', 4, 'TITULAR'),
    (305, 'Ahmed Hegazy', 26, null, 'Neom SC (KSA 2)', 5, 'TITULAR'),
    (306, 'Mohamed Hamdi', 26, null, 'Pyramids (EGY 1)', 6, 'TITULAR'),
    (307, 'Mohamed Elneny', 26, null, 'Al Jazira (UAE 1)', 7, 'TITULAR'),
    (308, 'Hamdi Fathi', 26, null, 'Al Wakrah (QAT 1)', 8, 'TITULAR'),
    (309, 'Omar Marmoush', 26, null, 'Manchester City (ENG 1)', 9, 'TITULAR'),
    (310, 'Mohamed Salah', 26, null, 'Liverpool (ENG 1)', 10, 'TITULAR'),
    (311, 'Mostafa Mohamed', 26, null, 'Nantes (FRA 1)', 11, 'TITULAR'),
    (312, 'Trézéguet', 26, null, 'Al Rayyan (QAT 1)', 12, 'TITULAR'),
    (313, 'Escudo de Irán', 27, null, null, 1, 'ESCUDO'),
    (314, 'Alireza Beiranvand', 27, null, 'Tractor (IRN 1)', 2, 'TITULAR'),
    (315, 'Ramin Rezaeian', 27, null, 'Esteghlal (IRN 1)', 3, 'TITULAR'),
    (316, 'Hossein Kanani', 27, null, 'Persepolis (IRN 1)', 4, 'TITULAR'),
    (317, 'Shoja Khalilzadeh', 27, null, 'Tractor (IRN 1)', 5, 'TITULAR'),
    (318, 'Milad Mohammadi', 27, null, 'Persepolis (IRN 1)', 6, 'TITULAR'),
    (319, 'Saeid Ezatolahi', 27, null, 'Shabab Al Ahli (UAE 1)', 7, 'TITULAR'),
    (320, 'Saman Ghoddos', 27, null, 'Kalba (UAE 1)', 8, 'TITULAR'),
    (321, 'Alireza Jahanbakhsh', 27, null, 'Heerenveen (NED 1)', 9, 'TITULAR'),
    (322, 'Mehdi Ghayedi', 27, null, 'Kalba (UAE 1)', 10, 'TITULAR'),
    (323, 'Mehdi Taremi', 27, null, 'Inter de Milán (ITA 1)', 11, 'TITULAR'),
    (324, 'Sardar Azmoun', 27, null, 'Shabab Al Ahli (UAE 1)', 12, 'TITULAR'),
    (325, 'Escudo de Nueva Zelanda', 28, null, null, 1, 'ESCUDO'),
    (326, 'Max Crocombe', 28, null, 'Burton Albion (ENG 3)', 2, 'TITULAR'),
    (327, 'Tim Payne', 28, null, 'Wellington Phoenix (NZL/AUS 1)', 3, 'TITULAR'),
    (328, 'Michael Boxall', 28, null, 'Minnesota United (USA 1)', 4, 'TITULAR'),
    (329, 'Tommy Smith', 28, null, 'Macarthur FC (AUS 1)', 5, 'TITULAR'),
    (330, 'Liberato Cacace', 28, null, 'Empoli (ITA 1)', 6, 'TITULAR'),
    (331, 'Joe Bell', 28, null, 'Viking FK (NOR 1)', 7, 'TITULAR'),
    (332, 'Marko Stamenic', 28, null, 'Olympiacos (GRE 1)', 8, 'TITULAR'),
    (333, 'Matthew Garbett', 28, null, 'NAC Breda (NED 1)', 9, 'TITULAR'),
    (334, 'Sarpreet Singh', 28, null, 'União de Leiria (POR 2)', 10, 'TITULAR'),
    (335, 'Chris Wood', 28, null, 'Nottingham Forest (ENG 1)', 11, 'TITULAR'),
    (336, 'Ben Waine', 28, null, 'Mansfield Town (ENG 3)', 12, 'TITULAR'),
    (337, 'Escudo de España', 29, null, null, 1, 'ESCUDO'),
    (338, 'Unai Simón', 29, null, 'Athletic Club (ESP 1)', 2, 'TITULAR'),
    (339, 'Dani Carvajal', 29, null, 'Real Madrid (ESP 1)', 3, 'TITULAR'),
    (340, 'Robin Le Normand', 29, null, 'Atlético Madrid (ESP 1)', 4, 'TITULAR'),
    (341, 'Aymeric Laporte', 29, null, 'Al Nassr (KSA 1)', 5, 'TITULAR'),
    (342, 'Marc Cucurella', 29, null, 'Chelsea (ENG 1)', 6, 'TITULAR'),
    (343, 'Rodri', 29, null, 'Manchester City (ENG 1)', 7, 'TITULAR'),
    (344, 'Pedri', 29, null, 'Barcelona (ESP 1)', 8, 'TITULAR'),
    (345, 'Fabián Ruiz', 29, null, 'Paris Saint-Germain (FRA 1)', 9, 'TITULAR'),
    (346, 'Lamine Yamal', 29, null, 'Barcelona (ESP 1)', 10, 'TITULAR'),
    (347, 'Álvaro Morata', 29, null, 'Galatasaray (TUR 1)', 11, 'TITULAR'),
    (348, 'Nico Williams', 29, null, 'Athletic Club (ESP 1)', 12, 'TITULAR'),
    (349, 'Escudo de Cabo Verde', 30, null, null, 1, 'ESCUDO'),
    (350, 'Vozinha', 30, null, 'Chaves (POR 2)', 2, 'TITULAR'),
    (351, 'Dylan Tavares', 30, null, 'Bastia (FRA 2)', 3, 'TITULAR'),
    (352, 'Roberto Lopes', 30, null, 'Shamrock Rovers (IRL 1)', 4, 'TITULAR'),
    (353, 'Logan Costa', 30, null, 'Villarreal (ESP 1)', 5, 'TITULAR'),
    (354, 'João Paulo Fernandes', 30, null, 'Sheriff Tiraspol (MDA 1)', 6, 'TITULAR'),
    (355, 'Kevin Pina', 30, null, 'Krasnodar (RUS 1)', 7, 'TITULAR'),
    (356, 'Patrick Andrade', 30, null, 'QarabaÄŸ (AZE 1)', 8, 'TITULAR'),
    (357, 'Jamiro Monteiro', 30, null, 'PEC Zwolle (NED 1)', 9, 'TITULAR'),
    (358, 'Jovane Cabral', 30, null, 'Estrela da Amadora (POR 1)', 10, 'TITULAR'),
    (359, 'Bebé', 30, null, 'Ibiza (ESP 3)', 11, 'TITULAR'),
    (360, 'Ryan Mendes', 30, null, 'Kocaelispor (TUR 2)', 12, 'TITULAR'),
    (361, 'Escudo de Arabia Saudita', 31, null, null, 1, 'ESCUDO'),
    (362, 'Mohammed Al-Owais', 31, null, 'Al Hilal (KSA 1)', 2, 'TITULAR'),
    (363, 'Saud Abdulhamid', 31, null, 'Roma (ITA 1)', 3, 'TITULAR'),
    (364, 'Abdulelah Al-Amri', 31, null, 'Al Ittihad (KSA 1)', 4, 'TITULAR'),
    (365, 'Ali Al-Bulayhi', 31, null, 'Al Hilal (KSA 1)', 5, 'TITULAR'),
    (366, 'Yasser Al-Shahrani', 31, null, 'Al Hilal (KSA 1)', 6, 'TITULAR'),
    (367, 'Mohamed Kanno', 31, null, 'Al Hilal (KSA 1)', 7, 'TITULAR'),
    (368, 'Abdulellah Al-Malki', 31, null, 'Al Ettifaq (KSA 1)', 8, 'TITULAR'),
    (369, 'Salem Al-Dawsari', 31, null, 'Al Hilal (KSA 1)', 9, 'TITULAR'),
    (370, 'Abdulrahman Ghareeb', 31, null, 'Al Nassr (KSA 1)', 10, 'TITULAR'),
    (371, 'Firas Al-Buraikan', 31, null, 'Al Ahli (KSA 1)', 11, 'TITULAR'),
    (372, 'Saleh Al-Shehri', 31, null, 'Al Ittihad (KSA 1)', 12, 'TITULAR'),
    (373, 'Escudo de Uruguay', 32, null, null, 1, 'ESCUDO'),
    (374, 'Sergio Rochet', 32, null, 'Internacional (BRA 1)', 2, 'TITULAR'),
    (375, 'Nahitan Nández', 32, null, 'Al Qadsiah (KSA 1)', 3, 'TITULAR'),
    (376, 'Ronald Araújo', 32, null, 'Barcelona (ESP 1)', 4, 'TITULAR'),
    (377, 'José María Giménez', 32, null, 'Atlético Madrid (ESP 1)', 5, 'TITULAR'),
    (378, 'Mathías Olivera', 32, null, 'Napoli (ITA 1)', 6, 'TITULAR'),
    (379, 'Manuel Ugarte', 32, null, 'Manchester United (ENG 1)', 7, 'TITULAR'),
    (380, 'Federico Valverde', 32, null, 'Real Madrid (ESP 1)', 8, 'TITULAR'),
    (381, 'Rodrigo Bentancur', 32, null, 'Tottenham Hotspur (ENG 1)', 9, 'TITULAR'),
    (382, 'Facundo Pellistri', 32, null, 'Panathinaikos (GRE 1)', 10, 'TITULAR'),
    (383, 'Darwin Núñez', 32, null, 'Liverpool (ENG 1)', 11, 'TITULAR'),
    (384, 'Giorgian De Arrascaeta', 32, null, 'Flamengo (BRA 1)', 12, 'TITULAR'),
    (385, 'Escudo de Francia', 33, null, null, 1, 'ESCUDO'),
    (386, 'Mike Maignan', 33, null, 'AC Milan (ITA 1)', 2, 'TITULAR'),
    (387, 'Jules Koundé', 33, null, 'Barcelona (ESP 1)', 3, 'TITULAR'),
    (388, 'William Saliba', 33, null, 'Arsenal (ENG 1)', 4, 'TITULAR'),
    (389, 'Dayot Upamecano', 33, null, 'Bayern Múnich (GER 1)', 5, 'TITULAR'),
    (390, 'Theo Hernández', 33, null, 'AC Milan (ITA 1)', 6, 'TITULAR'),
    (391, 'Aurélien Tchouaméni', 33, null, 'Real Madrid (ESP 1)', 7, 'TITULAR'),
    (392, 'Eduardo Camavinga', 33, null, 'Real Madrid (ESP 1)', 8, 'TITULAR'),
    (393, 'Antoine Griezmann', 33, null, 'Atlético Madrid (ESP 1)', 9, 'TITULAR'),
    (394, 'Ousmane Dembélé', 33, null, 'Paris Saint-Germain (FRA 1)', 10, 'TITULAR'),
    (395, 'Kylian Mbappé', 33, null, 'Real Madrid (ESP 1)', 11, 'TITULAR'),
    (396, 'Bradley Barcola', 33, null, 'Paris Saint-Germain (FRA 1)', 12, 'TITULAR'),
    (397, 'Escudo de Senegal', 34, null, null, 1, 'ESCUDO'),
    (398, 'Édouard Mendy', 34, null, 'Al Ahli (KSA 1)', 2, 'TITULAR'),
    (399, 'Youssouf Sabaly', 34, null, 'Betis (ESP 1)', 3, 'TITULAR'),
    (400, 'Kalidou Koulibaly', 34, null, 'Al Hilal (KSA 1)', 4, 'TITULAR'),
    (401, 'Moussa Niakhaté', 34, null, 'Lyon (FRA 1)', 5, 'TITULAR'),
    (402, 'Ismail Jakobs', 34, null, 'Galatasaray (TUR 1)', 6, 'TITULAR'),
    (403, 'Idrissa Gueye', 34, null, 'Everton (ENG 1)', 7, 'TITULAR'),
    (404, 'Pape Matar Sarr', 34, null, 'Tottenham Hotspur (ENG 1)', 8, 'TITULAR'),
    (405, 'Lamine Camara', 34, null, 'Monaco (FRA 1)', 9, 'TITULAR'),
    (406, 'Ismaïla Sarr', 34, null, 'Crystal Palace (ENG 1)', 10, 'TITULAR'),
    (407, 'Nicolas Jackson', 34, null, 'Chelsea (ENG 1)', 11, 'TITULAR'),
    (408, 'Sadio Mané', 34, null, 'Al Nassr (KSA 1)', 12, 'TITULAR'),
    (409, 'Escudo de Irak', 35, null, null, 1, 'ESCUDO'),
    (410, 'Jalal Hassan', 35, null, 'Al Zawraa (IRQ 1)', 2, 'TITULAR'),
    (411, 'Hussein Ali', 35, null, 'Heerenveen (NED 1)', 3, 'TITULAR'),
    (412, 'Rebin Sulaka', 35, null, 'FC Seoul (KOR 1)', 4, 'TITULAR'),
    (413, 'Saad Natiq', 35, null, 'Abha (KSA 2)', 5, 'TITULAR'),
    (414, 'Ali Adnan', 35, null, 'Mes Rafsanjan (IRN 1)', 6, 'TITULAR'),
    (415, 'Amjad Attwan', 35, null, 'Zakho (IRQ 1)', 7, 'TITULAR'),
    (416, 'Amir Al-Ammari', 35, null, 'Halmstads BK (SWE 1)', 8, 'TITULAR'),
    (417, 'Zidane Iqbal', 35, null, 'Utrecht (NED 1)', 9, 'TITULAR'),
    (418, 'Ali Jasim', 35, null, 'Como (ITA 1)', 10, 'TITULAR'),
    (419, 'Aymen Hussein', 35, null, 'Al Khor (QAT 1)', 11, 'TITULAR'),
    (420, 'Mohanad Ali', 35, null, 'Al Shorta (IRQ 1)', 12, 'TITULAR'),
    (421, 'Escudo de Noruega', 36, null, null, 1, 'ESCUDO'),
    (422, 'Ørjan Nyland', 36, null, 'Sevilla (ESP 1)', 2, 'TITULAR'),
    (423, 'Julian Ryerson', 36, null, 'Borussia Dortmund (GER 1)', 3, 'TITULAR'),
    (424, 'Kristoffer Ajer', 36, null, 'Brentford (ENG 1)', 4, 'TITULAR'),
    (425, 'Leo Østigård', 36, null, 'Hoffenheim (GER 1)', 5, 'TITULAR'),
    (426, 'Birger Meling', 36, null, 'FC Copenhague (DEN 1)', 6, 'TITULAR'),
    (427, 'Sander Berge', 36, null, 'Fulham (ENG 1)', 7, 'TITULAR'),
    (428, 'Fredrik Aursnes', 36, null, 'Benfica (POR 1)', 8, 'TITULAR'),
    (429, 'Martin Ødegaard', 36, null, 'Arsenal (ENG 1)', 9, 'TITULAR'),
    (430, 'Antonio Nusa', 36, null, 'RB Leipzig (GER 1)', 10, 'TITULAR'),
    (431, 'Erling Haaland', 36, null, 'Manchester City (ENG 1)', 11, 'TITULAR'),
    (432, 'Alexander Sørloth', 36, null, 'Atlético Madrid (ESP 1)', 12, 'TITULAR'),
    (433, 'Escudo de Argentina', 37, null, null, 1, 'ESCUDO'),
    (434, 'Emiliano Martínez', 37, null, 'Aston Villa (ENG 1)', 2, 'TITULAR'),
    (435, 'Nahuel Molina', 37, null, 'Atlético Madrid (ESP 1)', 3, 'TITULAR'),
    (436, 'Cristian Romero', 37, null, 'Tottenham Hotspur (ENG 1)', 4, 'TITULAR'),
    (437, 'Nicolás Otamendi', 37, null, 'Benfica (POR 1)', 5, 'TITULAR'),
    (438, 'Nicolás Tagliafico', 37, null, 'Lyon (FRA 1)', 6, 'TITULAR'),
    (439, 'Rodrigo De Paul', 37, null, 'Atlético Madrid (ESP 1)', 7, 'TITULAR'),
    (440, 'Enzo Fernández', 37, null, 'Chelsea (ENG 1)', 8, 'TITULAR'),
    (441, 'Alexis Mac Allister', 37, null, 'Liverpool (ENG 1)', 9, 'TITULAR'),
    (442, 'Lionel Messi', 37, null, 'Inter Miami (USA 1)', 10, 'TITULAR'),
    (443, 'Julián Álvarez', 37, null, 'Atlético Madrid (ESP 1)', 11, 'TITULAR'),
    (444, 'Lautaro Martínez', 37, null, 'Inter de Milán (ITA 1)', 12, 'TITULAR'),
    (445, 'Escudo de Argelia', 38, null, null, 1, 'ESCUDO'),
    (446, 'Anthony Mandrea', 38, null, 'Caen (FRA 2)', 2, 'TITULAR'),
    (447, 'Youcef Atal', 38, null, 'Al Sadd (QAT 1)', 3, 'TITULAR'),
    (448, 'Aïssa Mandi', 38, null, 'Lille (FRA 1)', 4, 'TITULAR'),
    (449, 'Ramy Bensebaïni', 38, null, 'Borussia Dortmund (GER 1)', 5, 'TITULAR'),
    (450, 'Rayan Aït-Nouri', 38, null, 'Wolverhampton (ENG 1)', 6, 'TITULAR'),
    (451, 'Ismaël Bennacer', 38, null, 'Olympique Marsella (FRA 1)', 7, 'TITULAR'),
    (452, 'Ramiz Zerrouki', 38, null, 'Feyenoord (NED 1)', 8, 'TITULAR'),
    (453, 'Houssem Aouar', 38, null, 'Al Ittihad (KSA 1)', 9, 'TITULAR'),
    (454, 'Riyad Mahrez', 38, null, 'Al Ahli (KSA 1)', 10, 'TITULAR'),
    (455, 'Amine Gouiri', 38, null, 'Olympique Marsella (FRA 1)', 11, 'TITULAR'),
    (456, 'Mohamed Amoura', 38, null, 'Wolfsburg (GER 1)', 12, 'TITULAR'),
    (457, 'Escudo de Austria', 39, null, null, 1, 'ESCUDO'),
    (458, 'Patrick Pentz', 39, null, 'Brøndby (DEN 1)', 2, 'TITULAR'),
    (459, 'Stefan Posch', 39, null, 'Atalanta (ITA 1)', 3, 'TITULAR'),
    (460, 'Philipp Lienhart', 39, null, 'Freiburg (GER 1)', 4, 'TITULAR'),
    (461, 'Kevin Danso', 39, null, 'Tottenham Hotspur (ENG 1)', 5, 'TITULAR'),
    (462, 'Phillipp Mwene', 39, null, 'Mainz 05 (GER 1)', 6, 'TITULAR'),
    (463, 'Nicolas Seiwald', 39, null, 'RB Leipzig (GER 1)', 7, 'TITULAR'),
    (464, 'Konrad Laimer', 39, null, 'Bayern Múnich (GER 1)', 8, 'TITULAR'),
    (465, 'Marcel Sabitzer', 39, null, 'Borussia Dortmund (GER 1)', 9, 'TITULAR'),
    (466, 'Christoph Baumgartner', 39, null, 'RB Leipzig (GER 1)', 10, 'TITULAR'),
    (467, 'Michael Gregoritsch', 39, null, 'Freiburg (GER 1)', 11, 'TITULAR'),
    (468, 'Marko ArnautoviÄ‡', 39, null, 'Inter de Milán (ITA 1)', 12, 'TITULAR'),
    (469, 'Escudo de Jordania', 40, null, null, 1, 'ESCUDO'),
    (470, 'Yazeed Abulaila', 40, null, 'Al Hussein (JOR 1)', 2, 'TITULAR'),
    (471, 'Ehsan Haddad', 40, null, 'Al Faisaly (JOR 1)', 3, 'TITULAR'),
    (472, 'Yazan Al-Arab', 40, null, 'Al Shorta (IRQ 1)', 4, 'TITULAR'),
    (473, 'Abdallah Nasib', 40, null, 'Al Hussein (JOR 1)', 5, 'TITULAR'),
    (474, 'Salem Al-Ajalin', 40, null, 'Al Faisaly (JOR 1)', 6, 'TITULAR'),
    (475, 'Nizar Al-Rashdan', 40, null, 'Al Hussein (JOR 1)', 7, 'TITULAR'),
    (476, 'Noor Al-Rawabdeh', 40, null, 'Selangor (MAS 1)', 8, 'TITULAR'),
    (477, 'Ali Olwan', 40, null, 'Selangor (MAS 1)', 9, 'TITULAR'),
    (478, 'Mousa Al-Tamari', 40, null, 'Rennes (FRA 1)', 10, 'TITULAR'),
    (479, 'Yazan Al-Naimat', 40, null, 'Al Ahli Doha (QAT 1)', 11, 'TITULAR'),
    (480, 'Mahmoud Al-Mardi', 40, null, 'Al Hussein (JOR 1)', 12, 'TITULAR'),
    (481, 'Escudo de Portugal', 41, null, null, 1, 'ESCUDO'),
    (482, 'Diogo Costa', 41, null, 'Porto (POR 1)', 2, 'TITULAR'),
    (483, 'João Cancelo', 41, null, 'Al Hilal (KSA 1)', 3, 'TITULAR'),
    (484, 'Rúben Dias', 41, null, 'Manchester City (ENG 1)', 4, 'TITULAR'),
    (485, 'António Silva', 41, null, 'Benfica (POR 1)', 5, 'TITULAR'),
    (486, 'Nuno Mendes', 41, null, 'Paris Saint-Germain (FRA 1)', 6, 'TITULAR'),
    (487, 'Vitinha', 41, null, 'Paris Saint-Germain (FRA 1)', 7, 'TITULAR'),
    (488, 'João Neves', 41, null, 'Paris Saint-Germain (FRA 1)', 8, 'TITULAR'),
    (489, 'Bruno Fernandes', 41, null, 'Manchester United (ENG 1)', 9, 'TITULAR'),
    (490, 'Bernardo Silva', 41, null, 'Manchester City (ENG 1)', 10, 'TITULAR'),
    (491, 'Cristiano Ronaldo', 41, null, 'Al Nassr (KSA 1)', 11, 'TITULAR'),
    (492, 'Rafael Leão', 41, null, 'AC Milan (ITA 1)', 12, 'TITULAR'),
    (493, 'Escudo de RD Congo', 42, null, null, 1, 'ESCUDO'),
    (494, 'Lionel Mpasi', 42, null, 'Rodez (FRA 2)', 2, 'TITULAR'),
    (495, 'Gédéon Kalulu', 42, null, 'Lorient (FRA 2)', 3, 'TITULAR'),
    (496, 'Chancel Mbemba', 42, null, 'Olympique Marsella (FRA 1)', 4, 'TITULAR'),
    (497, 'Dylan Batubinsika', 42, null, 'Saint-Étienne (FRA 1)', 5, 'TITULAR'),
    (498, 'Arthur Masuaku', 42, null, 'BeÅŸiktaÅŸ (TUR 1)', 6, 'TITULAR'),
    (499, 'Samuel Moutoussamy', 42, null, 'Sivasspor (TUR 1)', 7, 'TITULAR'),
    (500, 'Edo Kayembe', 42, null, 'Watford (ENG 2)', 8, 'TITULAR'),
    (501, 'Gaël Kakuta', 42, null, 'Esteghlal (IRN 1)', 9, 'TITULAR'),
    (502, 'Théo Bongonda', 42, null, 'Spartak Moscú (RUS 1)', 10, 'TITULAR'),
    (503, 'Cédric Bakambu', 42, null, 'Betis (ESP 1)', 11, 'TITULAR'),
    (504, 'Yoane Wissa', 42, null, 'Brentford (ENG 1)', 12, 'TITULAR'),
    (505, 'Escudo de Uzbekistán', 43, null, null, 1, 'ESCUDO'),
    (506, 'Utkir Yusupov', 43, null, 'Navbahor Namangan (UZB 1)', 2, 'TITULAR'),
    (507, 'Khojiakbar Alijonov', 43, null, 'Pakhtakor (UZB 1)', 3, 'TITULAR'),
    (508, 'Abdukodir Khusanov', 43, null, 'Manchester City (ENG 1)', 4, 'TITULAR'),
    (509, 'Rustam Ashurmatov', 43, null, 'Rubin Kazan (RUS 1)', 5, 'TITULAR'),
    (510, 'Farrukh Sayfiyev', 43, null, 'Pakhtakor (UZB 1)', 6, 'TITULAR'),
    (511, 'Otabek Shukurov', 43, null, 'Al Fayha (KSA 1)', 7, 'TITULAR'),
    (512, 'Jaloliddin Masharipov', 43, null, 'Esteghlal (IRN 1)', 8, 'TITULAR'),
    (513, 'Abbosbek Fayzullaev', 43, null, 'CSKA Moscú (RUS 1)', 9, 'TITULAR'),
    (514, 'Oston Urunov', 43, null, 'Persepolis (IRN 1)', 10, 'TITULAR'),
    (515, 'Eldor Shomurodov', 43, null, 'Roma (ITA 1)', 11, 'TITULAR'),
    (516, 'Igor Sergeev', 43, null, 'BG Pathum United (THA 1)', 12, 'TITULAR'),
    (517, 'Escudo de Colombia', 44, null, null, 1, 'ESCUDO'),
    (518, 'Camilo Vargas', 44, null, 'Atlas (MEX 1)', 2, 'TITULAR'),
    (519, 'Daniel Muñoz', 44, null, 'Crystal Palace (ENG 1)', 3, 'TITULAR'),
    (520, 'Davinson Sánchez', 44, null, 'Galatasaray (TUR 1)', 4, 'TITULAR'),
    (521, 'Jhon Lucumí', 44, null, 'Bologna (ITA 1)', 5, 'TITULAR'),
    (522, 'Johan Mojica', 44, null, 'Mallorca (ESP 1)', 6, 'TITULAR'),
    (523, 'Jefferson Lerma', 44, null, 'Crystal Palace (ENG 1)', 7, 'TITULAR'),
    (524, 'Richard Ríos', 44, null, 'Palmeiras (BRA 1)', 8, 'TITULAR'),
    (525, 'James Rodríguez', 44, null, 'León (MEX 1)', 9, 'TITULAR'),
    (526, 'Jhon Arias', 44, null, 'Fluminense (BRA 1)', 10, 'TITULAR'),
    (527, 'Jhon Durán', 44, null, 'Al Nassr (KSA 1)', 11, 'TITULAR'),
    (528, 'Luis Díaz', 44, null, 'Liverpool (ENG 1)', 12, 'TITULAR'),
    (529, 'Escudo de Inglaterra', 45, null, null, 1, 'ESCUDO'),
    (530, 'Jordan Pickford', 45, null, 'Everton (ENG 1)', 2, 'TITULAR'),
    (531, 'Reece James', 45, null, 'Chelsea (ENG 1)', 3, 'TITULAR'),
    (532, 'John Stones', 45, null, 'Manchester City (ENG 1)', 4, 'TITULAR'),
    (533, 'Marc Guéhi', 45, null, 'Crystal Palace (ENG 1)', 5, 'TITULAR'),
    (534, 'Ezri Konsa', 45, null, 'Aston Villa (ENG 1)', 6, 'TITULAR'),
    (535, 'Declan Rice', 45, null, 'Arsenal (ENG 1)', 7, 'TITULAR'),
    (536, 'Kobbie Mainoo', 45, null, 'Manchester United (ENG 1)', 8, 'TITULAR'),
    (537, 'Jude Bellingham', 45, null, 'Real Madrid (ESP 1)', 9, 'TITULAR'),
    (538, 'Bukayo Saka', 45, null, 'Arsenal (ENG 1)', 10, 'TITULAR'),
    (539, 'Harry Kane', 45, null, 'Bayern Múnich (GER 1)', 11, 'TITULAR'),
    (540, 'Marcus Rashford', 45, null, 'Aston Villa (ENG 1)', 12, 'TITULAR'),
    (541, 'Escudo de Croacia', 46, null, null, 1, 'ESCUDO'),
    (542, 'Dominik LivakoviÄ‡', 46, null, 'Fenerbahçe (TUR 1)', 2, 'TITULAR'),
    (543, 'Josip StaniÅ¡iÄ‡', 46, null, 'Bayern Múnich (GER 1)', 3, 'TITULAR'),
    (544, 'Josip Å utalo', 46, null, 'Ajax (NED 1)', 4, 'TITULAR'),
    (545, 'JoÅ¡ko Gvardiol', 46, null, 'Manchester City (ENG 1)', 5, 'TITULAR'),
    (546, 'Borna Sosa', 46, null, 'Torino (ITA 1)', 6, 'TITULAR'),
    (547, 'Luka ModriÄ‡', 46, null, 'Real Madrid (ESP 1)', 7, 'TITULAR'),
    (548, 'Mateo KovaÄiÄ‡', 46, null, 'Manchester City (ENG 1)', 8, 'TITULAR'),
    (549, 'Marcelo BrozoviÄ‡', 46, null, 'Al Nassr (KSA 1)', 9, 'TITULAR'),
    (550, 'Andrej KramariÄ‡', 46, null, 'Hoffenheim (GER 1)', 10, 'TITULAR'),
    (551, 'Ante Budimir', 46, null, 'Osasuna (ESP 1)', 11, 'TITULAR'),
    (552, 'Ivan PeriÅ¡iÄ‡', 46, null, 'PSV Eindhoven (NED 1)', 12, 'TITULAR'),
    (553, 'Escudo de Ghana', 47, null, null, 1, 'ESCUDO'),
    (554, 'Lawrence Ati-Zigi', 47, null, 'St. Gallen (SUI 1)', 2, 'TITULAR'),
    (555, 'Tariq Lamptey', 47, null, 'Brighton (ENG 1)', 3, 'TITULAR'),
    (556, 'Alexander Djiku', 47, null, 'Fenerbahçe (TUR 1)', 4, 'TITULAR'),
    (557, 'Mohammed Salisu', 47, null, 'Monaco (FRA 1)', 5, 'TITULAR'),
    (558, 'Gideon Mensah', 47, null, 'Auxerre (FRA 1)', 6, 'TITULAR'),
    (559, 'Thomas Partey', 47, null, 'Arsenal (ENG 1)', 7, 'TITULAR'),
    (560, 'Elisha Owusu', 47, null, 'Auxerre (FRA 1)', 8, 'TITULAR'),
    (561, 'Mohammed Kudus', 47, null, 'West Ham United (ENG 1)', 9, 'TITULAR'),
    (562, 'Jordan Ayew', 47, null, 'Leicester City (ENG 1)', 10, 'TITULAR'),
    (563, 'Iñaki Williams', 47, null, 'Athletic Club (ESP 1)', 11, 'TITULAR'),
    (564, 'Antoine Semenyo', 47, null, 'Bournemouth (ENG 1)', 12, 'TITULAR'),
    (565, 'Escudo de Panamá', 48, null, null, 1, 'ESCUDO'),
    (566, 'Orlando Mosquera', 48, null, 'Al Fayha (KSA 1)', 2, 'TITULAR'),
    (567, 'Michael Murillo', 48, null, 'Olympique Marsella (FRA 1)', 3, 'TITULAR'),
    (568, 'Fidel Escobar', 48, null, 'Saprissa (CRC 1)', 4, 'TITULAR'),
    (569, 'Edgardo Fariña', 48, null, 'Khimki (RUS 1)', 5, 'TITULAR'),
    (570, 'Eric Davis', 48, null, 'KoÅ¡ice (SVK 1)', 6, 'TITULAR'),
    (571, 'Aníbal Godoy', 48, null, 'San Diego FC (USA 1)', 7, 'TITULAR'),
    (572, 'Adalberto Carrasquilla', 48, null, 'Pumas UNAM (MEX 1)', 8, 'TITULAR'),
    (573, 'Cristian Martínez', 48, null, 'Al Jandal (KSA 2)', 9, 'TITULAR'),
    (574, 'Édgar Bárcenas', 48, null, 'Mazatlán (MEX 1)', 10, 'TITULAR'),
    (575, 'José Fajardo', 48, null, 'Universidad Católica (ECU 1)', 11, 'TITULAR'),
    (576, 'Ismael Díaz', 48, null, 'Universidad Católica (ECU 1)', 12, 'TITULAR');
UPDATE Figurita
SET imagen_url = '/spring/img/players/escudo-de-argentina.webp'
WHERE tipo = 'ESCUDO';

UPDATE Figurita
SET imagen_url = '/spring/img/players/emiliano-martinez.webp'
WHERE numero_dentro_del_pais = 2;

UPDATE Figurita
SET imagen_url = '/spring/img/players/nahuel-molina.webp'
WHERE numero_dentro_del_pais = 3;

UPDATE Figurita
SET imagen_url = '/spring/img/players/cristian-romero.webp'
WHERE numero_dentro_del_pais = 4;

UPDATE Figurita
SET imagen_url = '/spring/img/players/nicolas-otamendi.webp'
WHERE numero_dentro_del_pais = 5;

UPDATE Figurita
SET imagen_url = '/spring/img/players/nicolas-tagliafico.webp'
WHERE numero_dentro_del_pais = 6;

UPDATE Figurita
SET imagen_url = '/spring/img/players/rodrigo-de-paul.webp'
WHERE numero_dentro_del_pais = 7;

UPDATE Figurita
SET imagen_url = '/spring/img/players/enzo-fernandez.webp'
WHERE numero_dentro_del_pais = 8;

UPDATE Figurita
SET imagen_url = '/spring/img/players/alexis-mac-allister.webp'
WHERE numero_dentro_del_pais = 9;

UPDATE Figurita
SET imagen_url = '/spring/img/players/lionel-messi.webp'
WHERE numero_dentro_del_pais = 10;

UPDATE Figurita
SET imagen_url = '/spring/img/players/julian-alvarez.webp'
WHERE numero_dentro_del_pais = 11;

UPDATE Figurita
SET imagen_url = '/spring/img/players/lautaro-martinez.webp'
WHERE numero_dentro_del_pais = 12;

INSERT INTO Usuario (id, email, password, paquetes, paquetesPremium, intercambiosRealizados, monedas, activo, rol, pais)
VALUES (2, 'albumcompleto@test.com', '123456789', 0, 0, 0, 0, true, 'USER', 'Argentina');

INSERT INTO RelacionFiguritaUsuario (usuario_id, figurita_id, estaPegadaEnElAlbum)
SELECT 2, id, true
FROM Figurita;

INSERT INTO Album (
    usuario_id,
    total_figuritas,
    figuritas_pegadas,
    figuritas_faltantes,
    figuritas_repetidas
)
VALUES (2, 576, 576, 0, 0);

INSERT INTO Usuario (id, email, password, paquetes, paquetesPremium, intercambiosRealizados, monedas, activo, rol, pais)
VALUES
    (3, 'swap.argentina@test.com', '123456789', 25, 5, 0, 120, true, 'USER', 'Argentina'),
    (4, 'swap.brasil@test.com', '123456789', 25, 5, 0, 120, true, 'USER', 'Brasil'),
    (5, 'swap.portugal@test.com', '123456789', 25, 5, 0, 120, true, 'USER', 'Portugal');

INSERT INTO RelacionFiguritaUsuario (usuario_id, figurita_id, estaPegadaEnElAlbum)
VALUES
    (1, 10, true),
    (1, 10, false),
    (1, 22, true),
    (1, 22, false),

    (3, 433, true),
    (3, 433, false),
    (3, 434, true),
    (3, 434, false),
    (3, 435, true),
    (3, 435, false),
    (3, 436, false),
    (3, 437, false),

    (4, 97, true),
    (4, 97, false),
    (4, 98, true),
    (4, 98, false),
    (4, 99, true),
    (4, 99, false),
    (4, 100, false),
    (4, 101, false),

    (5, 481, true),
    (5, 481, false),
    (5, 482, true),
    (5, 482, false),
    (5, 483, true),
    (5, 483, false),
    (5, 484, false),
    (5, 485, false);

INSERT INTO Album (
    usuario_id,
    total_figuritas,
    figuritas_pegadas,
    figuritas_faltantes,
    figuritas_repetidas
)
VALUES
    (1, 576, 2, 574, 2),
    (3, 576, 3, 573, 3),
    (4, 576, 3, 573, 3),
    (5, 576, 3, 573, 3);

INSERT INTO PartidoProde (id, idApi, local, visitante, fecha, estado, golesLocal, golesVisitante)
VALUES
    (1, 1001, 'Francia', 'Suecia', '2026-06-30 22:00:00', 'FINALIZADO', 3, 0),
    (2, 1002, 'Mexico', 'Ecuador', '2026-07-01 22:00:00', 'FINALIZADO', 2, 0),
    (3, 1003, 'Inglaterra', 'Argentina', '2026-07-15 16:00:00', 'FINALIZADO', 1, 2),
    (4, 1004, 'Francia', 'Inglaterra', '2026-07-18 18:00:00', 'PROGRAMADO', null, null),
    (5, 1005, 'Espana', 'Argentina', '2026-07-19 16:00:00', 'PROGRAMADO', null, null);

INSERT INTO PronosticoProde (usuario_id, partido_id, golesLocal, golesVisitante, puntos, puntuado)
VALUES
    (1, 1, 3, 0, 6, true),
    (1, 2, 1, 0, 3, true),
    (1, 3, 1, 2, 6, true),
    (3, 1, 1, 2, 6, true),
    (4, 2, 2, 0, 0, true),
    (5, 1, 1, 3, 0, true);
